import { defineType, FieldDefinition, PreviewConfig } from "sanity";
import { GROUP, GROUPS, GroupValue } from "@/utils/constant";
import {
  createIdentityFields,
  createParentField,
  createSortOrderField,
  createPageSEOFields,
  createPagebuilderField,
} from "@/utils/factories/create-page-fields";
import { PageBuilderType } from "@/schemaTypes/definitions/pagebuilders";
import { GlobalType, GlobalFieldNames, GLOBAL_REGISTRY } from "../globals";
import { ComponentType, ReactNode } from "react";
import { PackageKey } from "./constant";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Parameters passed to initial value templates when creating a document.
 * These are provided by the Studio UI (page tree, create modal) and
 * used to wire up site context and parent relationships automatically.
 */
export interface TemplateParams {
  siteId: string;
  parentId?: string;
  title?: string;
}

/**
 * A Sanity initial value template generated by `definePackage`.
 * Spread these into your Sanity config's `schema.templates` array.
 */
export interface InitialValueTemplate {
  id: string;
  title: string;
  schemaType: string;
  icon?: ComponentType | ReactNode;
  parameters: Array<{ name: string; type: string }>;
  value: (params: TemplateParams) => Record<string, unknown>;
}

/**
 * Presentation overrides for a global document type within a package's
 * structure tool context. The global's schema is defined once centrally;
 * these options control how it appears in the Studio sidebar when this
 * package is enabled.
 *
 * @typeParam T - The global type name, used to constrain `defaultOrdering`
 *               fields to only those declared in the global's `sortFields`.
 */
export interface GlobalPresentationConfig<T extends GlobalType = GlobalType> {
  /** Override the display title in the structure tool */
  structureTitle?: string;

  /** Override the icon in the structure tool */
  icon?: ComponentType | ReactNode;

  /** Override default ordering — field names are constrained to this global's sortFields */
  defaultOrdering?: { field: GlobalFieldNames<T>; direction: "asc" | "desc" }[];
}

/**
 * Configuration for a single document role within a package.
 *
 * A "role" is a named slot in the package's document tree. Role keys are
 * freeform and semantic — use names that describe the document's purpose
 * (e.g. "hub", "featureGroup", "article", "topic"). Structural meaning
 * (entry points, parent-child relationships) is derived from
 * `allowPageAsParent` and `allowedParentRoles`, not from the key name.
 *
 * @typeParam K - Union of role keys defined in the parent `PackageConfig`.
 *               Used to constrain `allowedParentRoles` for type-safe
 *               autocomplete.
 */
export interface DocumentRoleConfig<K extends string = string> {
  /** Sanity schema type name, e.g. "saas.hub" or "kb.article" */
  name: string;

  /** Human-readable title shown in Studio, e.g. "Product Overview" */
  title: string;

  /** Icon shown in Studio lists and structure */
  icon: ComponentType | ReactNode;

  /** Description shown in package selection UI */
  description?: string;

  /**
   * Whether this document can be placed under a "page" document in the
   * site tree. This is the structural definition of an **entry point**.
   *
   * Typically true for root-level documents that need to appear in the
   * site's page tree. Documents without this flag (and without
   * `allowedParentRoles`) cannot be placed anywhere in the tree.
   *
   * @default false
   */
  allowPageAsParent?: boolean;

  /**
   * Which other roles within THIS package can be a parent of this document.
   * Uses role keys — resolved to Sanity type names automatically.
   *
   * A role can reference itself for recursive types (e.g. a topic that
   * can nest under another topic).
   *
   * @example
   * allowedParentRoles: ["hub"]            // can only live under the hub
   * allowedParentRoles: ["root", "topic"]  // under root, or nested under itself
   */
  allowedParentRoles?: NoInfer<K>[];

  /**
   * Pagebuilder type name. When provided, the document gets a pagebuilder
   * field. Typically used for entry-point documents that need flexible
   * page layouts.
   */
  pagebuilderType?: PageBuilderType;

  /** Type-specific fields appended after the common fields. */
  extraFields?: FieldDefinition[];

  /** Override the default preview config. */
  preview?: PreviewConfig;

  /** Override which group tab opens by default. */
  defaultGroup?: GroupValue;

  /** Whether the Studio UI allows setting/changing this document's parent. */
  setParentAllowed?: boolean;

  /**
   * Additional initial values for new documents of this type.
   *
   * The core fields (`site`, `parent`, `title`) are always set
   * automatically from the creation context. Values provided here
   * are merged on top — use this for type-specific defaults like
   * a default date, status, or category.
   *
   * Can be a static object or a function that receives the template
   * params and returns an object.
   *
   * @example
   * // Static extra values
   * initialValues: { status: "draft" }
   *
   * // Dynamic extra values
   * initialValues: (params) => ({
   *   publishedAt: new Date().toISOString().split("T")[0],
   * })
   */
  initialValues?:
    | Record<string, unknown>
    | ((params: TemplateParams) => Record<string, unknown>);
}

/**
 * Top-level configuration passed to `definePackage`.
 *
 * A package groups related document types into a logical unit that can be
 * enabled or disabled per site. The `documents` map uses freeform role
 * keys — structural meaning is derived from each role's config, not from
 * the key name.
 *
 * @typeParam K - Union of role keys, inferred from the `documents` object.
 */
export interface PackageConfig<K extends string = string> {
  /**
   * Unique key identifying this package, e.g. "articles", "commerce".
   * Used in the site's `enabledPackages` field and in lookup maps.
   */
  key: PackageKey;

  /** Human-readable package name, e.g. "Artikler", "Netthandel" */
  title: string;

  /**
   * Global document types this package uses when enabled.
   *
   * Pass `true` to include the global with default presentation, or
   * pass a `GlobalPresentationConfig` to override how it appears in
   * the structure tool.
   *
   * The global's schema is defined centrally — this only controls
   * whether it appears in the Studio sidebar and how it's presented
   * when this package is enabled on a site.
   *
   * @example
   * globals: {
   *   product: true,
   *   author: {
   *     structureTitle: "Produktforfattere",
   *     defaultOrdering: [{ field: "name", direction: "asc" }],
   *   },
   * }
   */
  globals?: { [G in GlobalType]?: boolean | GlobalPresentationConfig<G> };

  /**
   * Document roles in this package, keyed by semantic role name.
   *
   * Each key becomes a role identifier used in `allowedParentRoles`.
   * Structure (entry points, parent-child relationships) is derived
   * from each role's `allowPageAsParent` and `allowedParentRoles` config.
   *
   * @example
   * documents: {
   *   hub:          { name: "saas.hub", allowPageAsParent: true, ... },
   *   featureGroup: { name: "saas.featureGroup", allowedParentRoles: ["hub"], ... },
   *   feature:      { name: "saas.feature", allowedParentRoles: ["featureGroup"], ... },
   * }
   */
  documents: { [R in K]: DocumentRoleConfig<K> };
}

// ---------------------------------------------------------------------------
// Result types
// ---------------------------------------------------------------------------

/**
 * Resolved metadata for a single document role.
 *
 * This is what the Studio structure builder and document actions consume.
 * Parent relationships are fully resolved to Sanity type names.
 */
export interface DocumentRoleMeta {
  /** Sanity schema type name */
  type: string;

  /** Human-readable title */
  title: string;

  /** Studio icon */
  icon: ComponentType | ReactNode;

  /** Optional description for UI */
  description?: string;

  /** Generated template ID for creation flows (e.g. "pkg-commerce-catalog") */
  templateId: string;

  /** Whether the Studio UI allows changing this document's parent */
  setParentAllowed: boolean;

  /** The role key from the package config */
  role: string;

  /** Resolved Sanity type names that can be parents of this document */
  resolvedParentTypes: string[];

  /** Whether this document can live under a Page in the site tree */
  isEntryPoint: boolean;
}

/**
 * Resolved configuration for a global document type within a package.
 * Merges the package's presentation overrides with computed defaults.
 */
export interface ResolvedGlobalConfig {
  /** The global type name (e.g. "product", "author") */
  type: string;

  /** Display title for the structure tool */
  structureTitle: string;

  /** Unique ID for the structure tool list item (e.g. "global-commerce-product") */
  structureId: string;

  /** Icon for the structure tool, falls back to the global's own icon */
  icon?: ComponentType | ReactNode;

  /** GROQ filter for the document list, scoped to this package's documents */
  filter: string;

  /** Default ordering for the document list */
  defaultOrdering: { field: string; direction: "asc" | "desc" }[];
}

/**
 * The fully resolved output of `definePackage`.
 *
 * Contains Sanity schema definitions (ready to spread into your schema
 * array), initial value templates, and metadata the Studio uses for
 * structure building, document creation, and package management.
 *
 * @typeParam K - Union of role keys from the original config.
 */
export interface PackageResult<K extends string = string> {
  /** Unique package key */
  key: PackageKey;

  /** Human-readable title */
  title: string;

  /**
   * Sanity `defineType` results — spread these into your schema.
   * One entry per document role in the package.
   */
  schemas: ReturnType<typeof defineType>[];

  /**
   * Initial value templates for document creation.
   * Spread these into your Sanity config's `schema.templates` array.
   * One template per document role, with site/parent/title wiring built in.
   */
  templates: InitialValueTemplate[];

  /**
   * Resolved metadata for each document role, keyed by role name.
   * Use this for structure builder, document actions, and UI.
   */
  documents: Record<K, DocumentRoleMeta>;

  /**
   * Resolved globals config, keyed by global type name.
   * Used by the structure builder to create document lists.
   */
  globals: Record<string, ResolvedGlobalConfig>;
}

// ---------------------------------------------------------------------------
// Default preview
// ---------------------------------------------------------------------------

const defaultPreview: PreviewConfig = {
  select: {
    title: "title",
    slug: "slug.current",
    media: "ogImage",
    isPrivate: "seoNoIndex",
  },
  prepare: ({ title, slug, media, isPrivate }) => {
    const status = isPrivate ? "skjult" : "indeksert";
    return {
      title: title || "Side uten tittel",
      subtitle: slug ? `${slug} · ${status}` : status,
      media,
    };
  },
};

/** Standard template parameters for all package document templates. */
const TEMPLATE_PARAMETERS = [
  { name: "siteId", type: "string" },
  { name: "parentId", type: "string" },
  { name: "title", type: "string" },
] as const;

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Resolves role keys (e.g. "hub", "topic") into Sanity type names
 * (e.g. "saas.hub", "kb.topic"). Validates that referenced roles exist.
 */
function _resolveParentTypes(
  roleKey: string,
  roleConfig: DocumentRoleConfig<string>,
  allRoles: Record<string, DocumentRoleConfig<string>>,
): string[] {
  const parents = new Set<string>();

  if (roleConfig.allowPageAsParent) {
    parents.add("page");
  }

  for (const ref of roleConfig.allowedParentRoles ?? []) {
    if (allRoles[ref]) {
      parents.add(allRoles[ref].name);
    } else {
      throw new Error(
        `Role "${roleKey}" references parent role "${ref}" which does not exist in this package.`,
      );
    }
  }

  return Array.from(parents);
}

/**
 * Resolves the globals config from the package config into a map of
 * `ResolvedGlobalConfig` entries. Pulls default title, icon, and ordering
 * from the global's own definition (via `GLOBAL_REGISTRY`), then applies
 * any package-level overrides.
 *
 * The GROQ filter is scoped to only show globals that are referenced by
 * documents this package owns.
 */
function _resolveGlobals(
  packageKey: string,
  globalsConfig: PackageConfig["globals"],
  packageDocumentTypes: string[],
): Record<string, ResolvedGlobalConfig> {
  const resolved: Record<string, ResolvedGlobalConfig> = {};

  if (!globalsConfig) return resolved;

  for (const [globalType, config] of Object.entries(globalsConfig)) {
    if (!config) continue;

    const globalDef = GLOBAL_REGISTRY[globalType as GlobalType];
    const overrides = typeof config === "boolean" ? {} : config;

    // Runtime validation: ensure ordering fields exist in sortFields
    if (overrides.defaultOrdering && globalDef) {
      const validFields = new Set(globalDef.sortFields);
      for (const ordering of overrides.defaultOrdering) {
        if (!validFields.has(ordering.field)) {
          throw new Error(
            `Global "${globalType}" has no sortable field "${ordering.field}". ` +
              `Available sort fields: ${globalDef.sortFields.join(", ")}`,
          );
        }
      }
    }

    const typeList = JSON.stringify(packageDocumentTypes);

    resolved[globalType] = {
      type: globalType,
      structureTitle:
        overrides.structureTitle ?? globalDef?.schema.title ?? globalType,
      structureId: `global-${packageKey}-${globalType}`,
      icon: overrides.icon ?? globalDef?.schema.icon,
      filter: `_type == "${globalType}" && count(*[_type in ${typeList} && references(^._id)]) > 0`,
      defaultOrdering: overrides.defaultOrdering ?? [
        {
          field: globalDef?.sortFields[0] ?? "title",
          direction: "asc" as const,
        },
      ],
    };
  }

  return resolved;
}

/**
 * Builds an initial value template for a document role.
 * Handles site/parent/title wiring automatically, then merges any
 * consumer-provided initial values on top.
 */
function _buildTemplate(
  packageKey: string,
  roleKey: string,
  roleConfig: DocumentRoleConfig<string>,
): InitialValueTemplate {
  const templateId = `pkg-${packageKey}-${roleKey}-template`;

  return {
    id: templateId,
    title: roleConfig.title,
    schemaType: roleConfig.name,
    icon: roleConfig.icon,
    parameters: [...TEMPLATE_PARAMETERS],
    value: (params: TemplateParams) => {

      // Core fields — always set from creation context
      const base: Record<string, unknown> = {};

      if (params.title) {
        base.title = params.title;
      }

      if (params.siteId) {
        base.site = { _type: "reference", _ref: params.siteId };
      }

      if (params.parentId) {
        base.parent = { _type: "reference", _ref: params.parentId };
      }

      // Consumer-provided extra values
      const extra =
        typeof roleConfig.initialValues === "function"
          ? roleConfig.initialValues(params)
          : (roleConfig.initialValues ?? {});

      // Extra values merge on top, but core fields always win
      return { ...extra, ...base };
    },
  };
}

/**
 * Assembles the full field list for a document role.
 */
function _buildFields(
  role: DocumentRoleConfig<string>,
  resolvedParentTypes: string[],
): FieldDefinition[] {
  const { pagebuilderType, extraFields = [] } = role;

  return [
    ...createIdentityFields(),
    ...createParentField(resolvedParentTypes),
    ...createSortOrderField(),
    ...createPageSEOFields(),
    ...(pagebuilderType ? createPagebuilderField(pagebuilderType) : []),
    ...extraFields,
  ];
}

// ---------------------------------------------------------------------------
// Factory
// ---------------------------------------------------------------------------

/**
 * Define a complete package: schemas + metadata + templates in one declaration.
 *
 * This is the primary entry point for extending the system with new
 * content types. Each call produces:
 *
 * 1. Sanity schema definitions for every document role.
 * 2. Initial value templates with automatic site/parent/title wiring.
 * 3. Metadata for structure building, document creation, and package management.
 *
 * Role keys are freeform — use descriptive names like `"hub"`,
 * `"featureGroup"`, `"article"`. Structure is derived from each
 * role's `allowPageAsParent` and `allowedParentRoles` config.
 * TypeScript provides full autocomplete on `allowedParentRoles`
 * based on the keys you define.
 *
 * @example
 * ```ts
 * const commerce = definePackage({
 *   key: "commerce",
 *   title: "Netthandel",
 *   globals: {
 *     product: {
 *       structureTitle: "Produkter",
 *       defaultOrdering: [{ field: "title", direction: "asc" }],
 *     },
 *   },
 *   documents: {
 *     catalog: {
 *       name: "catalogRoot",
 *       title: "Katalog",
 *       icon: ShoppingCart,
 *       allowPageAsParent: true,
 *       pagebuilderType: "catalogRootPageBuilder",
 *     },
 *     productPage: {
 *       name: "productPage",
 *       title: "Produktside",
 *       icon: PackageIcon,
 *       allowedParentRoles: ["catalog"],
 *       initialValues: {
 *         publishedAt: new Date().toISOString().split("T")[0],
 *       },
 *     },
 *   },
 * });
 *
 * // Register in Sanity config:
 * const schemas = [...commerce.schemas];
 * const templates = (prev) => [...prev, ...commerce.templates];
 *
 * // Access metadata:
 * commerce.documents.catalog.templateId     // "pkg-commerce-catalog"
 * commerce.documents.catalog.isEntryPoint   // true
 * commerce.documents.productPage.resolvedParentTypes // ["catalogRoot"]
 * ```
 */
export function definePackage<K extends string>(
  config: PackageConfig<K>,
): PackageResult<K> {
  const { key, title, documents } = config;

  const schemas: ReturnType<typeof defineType>[] = [];
  const templates: InitialValueTemplate[] = [];
  const documentsMeta = {} as Record<K, DocumentRoleMeta>;

  for (const [roleKey, roleConfig] of Object.entries<DocumentRoleConfig<K>>(
    documents,
  )) {
    const resolvedParentTypes = _resolveParentTypes(
      roleKey,
      roleConfig,
      documents,
    );

    const templateId = `pkg-${key}-${roleKey}-template`;

    // Build schema
    const schema = defineType({
      name: roleConfig.name,
      title: roleConfig.title,
      type: "document",
      icon: roleConfig.icon,
      groups: GROUPS(roleConfig.defaultGroup ?? GROUP.IDENTITY),
      fields: _buildFields(roleConfig, resolvedParentTypes),
      preview: roleConfig.preview ?? defaultPreview,
    });

    schemas.push(schema);

    // Build template
    templates.push(_buildTemplate(key, roleKey, roleConfig));

    // Build metadata
    documentsMeta[roleKey as K] = {
      type: roleConfig.name,
      title: roleConfig.title,
      icon: roleConfig.icon,
      description: roleConfig.description,
      templateId,
      setParentAllowed: roleConfig.setParentAllowed ?? false,
      role: roleKey,
      resolvedParentTypes,
      isEntryPoint: !!roleConfig.allowPageAsParent,
    };
  }

  const packageDocumentTypes = Object.values<DocumentRoleConfig<K>>(
    documents,
  ).map((r) => r.name);
  const globals = _resolveGlobals(key, config.globals, packageDocumentTypes);

  return { key, title, schemas, templates, documents: documentsMeta, globals };
}

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

/**
 * Create lookup maps and constants from an array of PackageResults.
 *
 * Call this once after defining all packages. The registry validates
 * that document type names are unique across packages, derives
 * entry points from config, and provides lookup helpers for the
 * Studio structure builder and document actions.
 *
 * @example
 * ```ts
 * const articles = definePackage({ ... });
 * const commerce = definePackage({ ... });
 *
 * export const registry = createPackageRegistry([articles, commerce]);
 *
 * registry.allSchemas              // every schema from every package
 * registry.allTemplates            // every template, ready for schema.templates
 * registry.allEntryTypes           // ["page", "catalogRoot", ...]
 * registry.lookup("productPage")   // { package, meta } or undefined
 * registry.globalsForPackages(["commerce"]) // resolved globals for enabled pkgs
 * ```
 */
export function createPackageRegistry(packages: PackageResult<string>[]) {
  const allSchemas = packages.flatMap((pkg) => pkg.schemas);
  const allTemplates = packages.flatMap((pkg) => pkg.templates);

  const byType = new Map<
    string,
    { package: PackageResult<string>; meta: DocumentRoleMeta }
  >();
  const byKey = new Map<string, PackageResult<string>>();
  const entryPointTypes = new Set<string>(["page"]);

  for (const pkg of packages) {
    if (byKey.has(pkg.key)) {
      throw new Error(
        `Duplicate package key "${pkg.key}". Package keys must be unique.`,
      );
    }
    byKey.set(pkg.key, pkg);

    for (const meta of Object.values<DocumentRoleMeta>(pkg.documents)) {
      if (byType.has(meta.type)) {
        const existing = byType.get(meta.type)!;
        throw new Error(
          `Duplicate document type "${meta.type}" found in packages "${existing.package.key}" and "${pkg.key}". Document type names must be unique.`,
        );
      }

      byType.set(meta.type, { package: pkg, meta });

      if (meta.isEntryPoint) {
        entryPointTypes.add(meta.type);
      }
    }
  }

  return {
    /** All registered packages */
    packages,

    /** Every schema from every package, ready to spread into Sanity config */
    allSchemas,

    /**
     * Every initial value template from every package.
     * Use in your Sanity config: `schema.templates: (prev) => [...prev, ...registry.allTemplates]`
     */
    allTemplates,

    /** All document types that can appear at the top level of the site tree */
    allEntryTypes: Array.from(entryPointTypes),

    /** For UI dropdowns (site's enabledPackages field, etc.) */
    packageOptions: packages.map((pkg) => ({
      title: pkg.title,
      value: pkg.key,
    })),

    /** Find the package and role metadata for any Sanity type name */
    lookup: (typeName: string) => byType.get(typeName),

    /** Find a package by its key */
    getPackage: (key: string) => byKey.get(key),

    /**
     * Collect resolved globals for a set of enabled package keys.
     * Each package gets its own entries — if multiple packages claim
     * the same global type, each appears with its own presentation
     * config and package-scoped filter.
     */
    globalsForPackages: (
      enabledKeys: string[],
    ): Array<ResolvedGlobalConfig & { packageKey: string }> => {
      const result: Array<ResolvedGlobalConfig & { packageKey: string }> = [];

      for (const key of enabledKeys) {
        const pkg = byKey.get(key);
        if (!pkg) continue;

        for (const config of Object.values(pkg.globals)) {
          result.push({ ...config, packageKey: key });
        }
      }

      return result;
    },
  };
}
